### ISSUE TITLE
[Build] Refactor and Upgrade to OpenSearch 2.10

### ISSUE THREAD

**Issue by macohen** [opensearch-project/opensearch-learning-to-rank-base#23]
### Is your feature request related to a problem?
Created a new branch for OpenSearch 2.10, but there is refactoring to do to build successfully.

 opensearch-learning-to-rank-base % ./gradlew -Dopensearch.version=2.10.0 -Djava.security.manager=allow -Dbuild.snapshot=false build 

Removed the stack trace for less noise.

### What solution would you like?
Successful build including integ tests.

**Comment by macohen** [comment]
I've made a bunch of changes to get the plugin to compile on 2.10. Most tests also pass, but I'm not quite sure how to replace toXContent methods since the changes in 2.9 from core. I believe 5 tests are failing. @noCharger I might be able to take a look late this week, but if you feel like giving it a shot, my latest is here: https://github.com/macohen/opensearch-learning-to-rank-base/tree/2.10

**Comment by jzonthemtn** [comment]
@macohen I see this is building now and there's a release for 2.11.1 now. Does that mean this issue can be closed? If so, I can work on a 2.12.0 version.
