### ISSUE TITLE
Build LTR plugin for OpenSearch >= 2.13.0

### ISSUE THREAD

**Issue by jzonthemtn** [opensearch-project/opensearch-learning-to-rank-base#33]
Build for OpenSearch 2.13.0.

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/dbwiddis) [3](https://github.com/krisfreedain) [4](https://github.com/akolarkunnu) [5](https://github.com/mingshl) [6](https://github.com/getsaurabh02)

**Comment by dblock** [comment]
I think we need 1-click release automation for this plugin so that it can follow the release cycle of OpenSearch. Maybe someone can work with @getsaurabh02 on this?
