### ISSUE TITLE
Build LTR plugin for OpenSearch 2.14.0.

### ISSUE THREAD

**Issue by jzonthemtn** [opensearch-project/opensearch-learning-to-rank-base#34]
Build LTR plugin for OpenSearch 2.14.0.

**Comment by macohen** [comment]
@jzonthemtn I finally merged this, but there are tests failing in the build. Can you take a look, please? [Changes to build for OpenSearch 2.14.0 (#35)](https://github.com/opensearch-project/opensearch-learning-to-rank-base/actions/runs/10832091615)

**Comment by jzonthemtn** [comment]
Thanks! Yes, will do. I *think* there are some tests that fail intermittently (which isn't good regardless) but I will dig into it.
