### ISSUE TITLE
Build LTR plugin for OpenSearch 2.15.0

### ISSUE THREAD

**Issue by quorcs** [opensearch-project/opensearch-learning-to-rank-base#38]
Build LTR plugin for OpenSearch 2.15.0

**Comment by jzonthemtn** [comment]
Similar to #34, probably best to see if we can get the plugin integrated with the OpenSearch release process.

**Comment by quorcs** [comment]
@jzonthemtn i up open search version to 2.15 but i have same test problems (https://github.com/quorcs/opensearch-learning-to-rank-base). I skipped tests and build the plugin. now my colleagues try to testing it

**Comment by dblock** [comment]
Including the plugin into the full release is a good idea, but that is a long conversation. I recommend fixing up the repo and releasing 2.15 of this plugin.

If someone can help get this plugin to branch on main with OpenSearch 3.0 and on 2.x with 2.x, and do the work of bumping versions, the infrastructure team can help with setting up 1-click release. You can work with @gaiksaya on the latter.

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/krisfreedain), [3](https://github.com/andrross), [4](https://github.com/reta)]

**Comment by epugh** [comment]
^^ @sstults I think the comment above from @dblock lays out what we need to get done.....    I almost want to suggest we rename this Issue to "Build LTR plugin for OpenSearch 2.11 to 2.17"!
