### ISSUE TITLE
[BUG] The docs refer to the demo directory, however it isn't in our code base.

### ISSUE THREAD

**Issue by epugh** [opensearch-project/opensearch-learning-to-rank-base#43]
### What is the bug?
In the docs, that we are coping over, we have http://localhost:4000/docs/latest/search-plugins/ltr/logging-features/ page that says:

![image](https://github.com/user-attachments/assets/b2e129fd-6168-457c-a0ff-40f22249515e)

However, that link, which should be https://github.com/o19s/OpenSearch-learning-to-rank/tree/master/demo doesn't work because that directory was never ported over.

### How can one reproduce the bug?
Use this PR for the documentation and stand it up: https://github.com/opensearch-project/documentation-website/pull/8336

### What is the expected behavior?
Either the link works, or we rework it to not have a link

**Comment by epugh** [comment]
Good candidate for @johannesdaniel to pick up...

**Comment by dblock** [comment]
[Catch All [Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/dblock), [2](https://github.com/reta),  [3](https://github.com/krisfreedain),  [4](https://github.com/lukas-vlcek/)]

**Comment by sstults** [comment]
@epugh it looks like this was edited out of the docs. Okay to close?

**Comment by epugh** [comment]
I suppose so...    Did we add back the docs though?   I see https://github.com/opensearch-project/opensearch-learning-to-rank-base/tree/main/demo, is that the missing dir?   Looking back at the original docs, they pointed to https://github.com/o19s/elasticsearch-learning-to-rank/tree/main/demo.

So I think the right fix is to add a PR to the docs website restoring the link to our `demo` dir...!

**Comment by sstults** [comment]
I agree. After doing a bit of code archeology I found that most of what was in the demo directory was moved to hello-ltr. So, the link at the top of the page should go to that site instead of referencing this demo directory.

opensearch-project/documentation-website#8795
