### ISSUE TITLE
[FEATURE] Add features to improve maintainability of plugin in managed service

### ISSUE THREAD

**Issue by JohannesDaniel** [opensearch-project/opensearch-learning-to-rank-base#62]
The goal is to improve the maintainability of the plugin to run it within a managed service. For this purpose, three core components are implemented:

### Circuit breaker
The main purpose of this feature is to protect resources such as CPU or memory in a managed service and to throw exceptions for the case that resources are exceeded.

### Settings
The settings enable to check whether the plugin is active or whether the breaker is active. The check for the plugin activeness is happening for each REST call in order to ensure that the plugin is only used for the case that it has been activated beforehand.

### Stats
The stats give insights about the plugin health and cache usage. Exceptions being thrown during requests are counted and made available. Furthermore the basic information about the index used to store models or features are provided.

**Comment by kkhatua** [comment]
@JohannesDaniel 
Can you add more details based on the issue template ? In the current form the context is missing and raises more questions.
(@epugh mentioned you missed joining the Wed session on Search community meeting on Zoom, so sharing my comments here)

My first impression was that you were looking for a way to expose the settings for LTR for users to configure. APIs are the right way to do this, but if one doesn't have direct access to the physical hosts, dashboards is a natural way to go. Whether it makes sense for LTR to spin its own dashboard or piggy back of something more generic in that space (e.g. Search Relevancy) is somethign worth considering. 

As a glance through the code, you also appear to be introducing stats for the LTR plugin. If so, I would suggest keeping the two separate as the former (e.g. configuring via dashboard) builds on the latter (existing stats APIs). This way your code will get easier to review and you can also test for backward compatibility between versions that support your feature and those that don't.
