### ISSUE TITLE
[PROPOSAL] Make new release  2.18.0

### ISSUE THREAD

**Issue by romashqua** [opensearch-project/opensearch-learning-to-rank-base#68]
Hello, plz make new release  2.18.0, because we see approved PR  (https://github.com/opensearch-project/opensearch-learning-to-rank-base/pull/67) in to branch  https://github.com/opensearch-project/opensearch-learning-to-rank-base/tree/2.x.
thx,))

**Comment by Biowoolf** [comment]
yeah will be good - waiting for it a lot

**Comment by sstults** [comment]
[Release 2.18.0](https://github.com/opensearch-project/opensearch-learning-to-rank-base/releases/tag/v2.18.0) has been added. Please let us know if you see any issues.
